import type { POI } from "@/lib/domain/types";

const verifiedAt = "2026-07-15T00:00:00.000Z";
const alpineClubLink = "https://www.alpineclub.org.pk/";

/**
 * Curated POIs are deliberately explicit rather than generated from a map API.
 * This is the grounding catalogue used by the mock itinerary generator.
 */
export const pois: POI[] = [
  // Hunza
  {
    id: "poi-attabad-lake",
    name: "Attabad Lake",
    slug: "attabad-lake",
    regionId: "region-hunza",
    category: "LAKE",
    latitude: 36.3257,
    longitude: 74.8727,
    description:
      "A striking turquoise lake formed after the 2010 Attabad landslide. Take a boat ride, then pause at the tunnel viewpoints along the Karakoram Highway.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2560,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 0,
    safetyNotes:
      "Wear a buoyancy aid for boat trips and ask locally about wind conditions before going out on the water.",
    photos: [
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-baltit-fort",
    name: "Baltit Fort",
    slug: "baltit-fort",
    regionId: "region-hunza",
    category: "FORT",
    latitude: 36.3243,
    longitude: 74.6679,
    description:
      "A 700-year-old fort above Karimabad, restored as a museum of Hunza's royal history, timber craftsmanship and mountain trade routes.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2500,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 1200,
    photos: [
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-altit-fort",
    name: "Altit Fort",
    slug: "altit-fort",
    regionId: "region-hunza",
    category: "FORT",
    latitude: 36.3225,
    longitude: 74.6944,
    description:
      "Hunza's older royal fort, paired with the carefully restored Altit village and its terraced gardens above the Hunza River.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2500,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 1000,
    photos: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-eagles-nest-duikar",
    name: "Eagle's Nest, Duikar",
    slug: "eagles-nest-duikar",
    regionId: "region-hunza",
    category: "VIEWPOINT",
    latitude: 36.3284,
    longitude: 74.6545,
    description:
      "A high lookout above Karimabad known for broad sunrise and sunset views across the Hunza and Nagar valleys.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2850,
    requiresPermit: false,
    roadCondition: "UNPAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    safetyNotes:
      "The final climb is steep and narrow. Use a local driver after dark and carry a warm layer even in summer.",
    photos: [
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-passu-cones",
    name: "Passu Cones Viewpoint",
    slug: "passu-cones-viewpoint",
    regionId: "region-hunza",
    category: "MOUNTAIN",
    latitude: 36.4621,
    longitude: 74.8923,
    description:
      "A roadside view to the cathedral-like Passu Cones and the glacier valley beyond; light is especially good early and late in the day.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2550,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-hussaini-bridge",
    name: "Hussaini Suspension Bridge",
    slug: "hussaini-suspension-bridge",
    regionId: "region-hunza",
    category: "VIEWPOINT",
    latitude: 36.456,
    longitude: 74.8933,
    description:
      "A long plank-and-cable suspension bridge over the Hunza River near Hussaini village, best approached calmly and with sensible footwear.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2540,
    requiresPermit: false,
    roadCondition: "UNPAVED",
    avgVisitHours: 1,
    entryFeePkr: 500,
    safetyNotes:
      "Cross only when the bridge is open and conditions are calm. It is not suitable for anyone uncomfortable with exposed heights.",
    photos: [
      "https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-khunjerab-pass",
    name: "Khunjerab Pass",
    slug: "khunjerab-pass",
    regionId: "region-hunza",
    category: "MOUNTAIN",
    latitude: 36.8508,
    longitude: 75.4306,
    description:
      "The high Pakistan–China border crossing at the top of the Karakoram Highway, with dramatic open plateau scenery and severe altitude.",
    bestSeasons: ["SUMMER", "AUTUMN"],
    altitudeMeters: 4693,
    requiresPermit: false,
    roadCondition: "SEASONAL_CLOSURE",
    avgVisitHours: 4,
    entryFeePkr: 0,
    safetyNotes:
      "The road typically closes with winter snow. Go only after checking current official/local road status; altitude symptoms are common at this height.",
    photos: [
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-kilik-mintaka-trek",
    name: "Kilik & Mintaka Pass Trek",
    slug: "kilik-mintaka-pass-trek",
    regionId: "region-hunza",
    category: "MOUNTAIN",
    latitude: 36.9587,
    longitude: 74.6746,
    description:
      "A remote high-altitude trek in upper Chapursan toward historic Silk Road passes near the Afghan and Chinese border areas.",
    bestSeasons: ["SUMMER"],
    altitudeMeters: 4700,
    requiresPermit: true,
    permitAuthority: "Gilgit-Baltistan local administration and licensed trekking operator",
    permitNotes:
      "Border-zone access is controlled. Foreign and independent travelers should arrange clearance and a qualified local operator before committing transport or trekking days.",
    permitOfficialLink: alpineClubLink,
    permitLastVerifiedAt: verifiedAt,
    roadCondition: "FOUR_WD_REQUIRED",
    avgVisitHours: 8,
    entryFeePkr: 0,
    safetyNotes:
      "High altitude, sparse services and changing border-area rules make this an expedition-style activity, not a casual day trip.",
    photos: [
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },

  // Skardu
  {
    id: "poi-shangrila-lake",
    name: "Lower Kachura Lake (Shangrila)",
    slug: "lower-kachura-lake-shangrila",
    regionId: "region-skardu",
    category: "LAKE",
    latitude: 35.2857,
    longitude: 75.6298,
    description:
      "A calm lake south of Skardu framed by poplars and steep brown mountains, with easy paths and classic first-day scenery.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2500,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 1500,
    photos: [
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-upper-kachura-lake",
    name: "Upper Kachura Lake",
    slug: "upper-kachura-lake",
    regionId: "region-skardu",
    category: "LAKE",
    latitude: 35.285,
    longitude: 75.6567,
    description:
      "A clearer, quieter lake beyond Lower Kachura, reached by a short rough approach and ideal for an unhurried lakeside afternoon.",
    bestSeasons: ["SUMMER", "AUTUMN"],
    altitudeMeters: 2500,
    requiresPermit: false,
    roadCondition: "UNPAVED",
    avgVisitHours: 2.5,
    entryFeePkr: 500,
    photos: [
      "https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-shigar-fort",
    name: "Shigar Fort",
    slug: "shigar-fort",
    regionId: "region-skardu",
    category: "FORT",
    latitude: 35.4216,
    longitude: 75.7349,
    description:
      "A 17th-century Balti fort and museum restored in the Shigar Valley, with a beautiful old village walk around it.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2230,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 1000,
    photos: [
      "https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-deosai-plains",
    name: "Deosai Plains",
    slug: "deosai-plains",
    regionId: "region-skardu",
    category: "NATIONAL_PARK",
    latitude: 35.0301,
    longitude: 75.4285,
    description:
      "A vast high plateau of wildflowers, streams and brown-bear habitat, often called the Roof of the World.",
    bestSeasons: ["SUMMER"],
    altitudeMeters: 4114,
    requiresPermit: false,
    roadCondition: "SEASONAL_CLOSURE",
    avgVisitHours: 7,
    entryFeePkr: 1000,
    safetyNotes:
      "Open roughly June to September only. Bring warm layers, sun protection, water and enough time to acclimatise to the altitude.",
    photos: [
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-manthoka-waterfall",
    name: "Manthoka Waterfall",
    slug: "manthoka-waterfall",
    regionId: "region-skardu",
    category: "WATERFALL",
    latitude: 35.5158,
    longitude: 75.9742,
    description:
      "A broad, cold waterfall in Kharmang District, surrounded by cultivated fields and a popular summer picnic area.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 1800,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 300,
    photos: [
      "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-basho-valley",
    name: "Basho Valley",
    slug: "basho-valley",
    regionId: "region-skardu",
    category: "VALLEY",
    latitude: 35.4224,
    longitude: 75.9907,
    description:
      "A green side valley of pine forests, river crossings and open meadows east of Skardu, rewarding a full jeep day.",
    bestSeasons: ["SUMMER", "AUTUMN"],
    altitudeMeters: 2900,
    requiresPermit: false,
    roadCondition: "FOUR_WD_REQUIRED",
    avgVisitHours: 7,
    entryFeePkr: 0,
    safetyNotes:
      "Use an experienced local 4x4 driver; road surfaces and stream crossings change with weather.",
    photos: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-katpana-desert",
    name: "Katpana Cold Desert",
    slug: "katpana-cold-desert",
    regionId: "region-skardu",
    category: "VIEWPOINT",
    latitude: 35.3091,
    longitude: 75.6048,
    description:
      "Silver sand dunes edged by snow-lined mountains just outside Skardu, particularly atmospheric near sunrise and sunset.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2226,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-satpara-lake",
    name: "Satpara Lake",
    slug: "satpara-lake",
    regionId: "region-skardu",
    category: "LAKE",
    latitude: 35.2234,
    longitude: 75.6696,
    description:
      "A deep blue reservoir beneath the Deosai approach, with a mountain backdrop and convenient stops from Skardu town.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2636,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-k2-concordia-trek",
    name: "K2 Base Camp & Concordia Trek",
    slug: "k2-base-camp-concordia-trek",
    regionId: "region-skardu",
    category: "GLACIER",
    latitude: 35.8803,
    longitude: 76.5141,
    description:
      "Pakistan's iconic multi-day Baltoro Glacier expedition to Concordia and the base of K2; this is not a day excursion from Skardu.",
    bestSeasons: ["SUMMER"],
    altitudeMeters: 5000,
    requiresPermit: true,
    permitAuthority: "Alpine Club of Pakistan via a licensed trekking operator",
    permitNotes:
      "Foreign trekkers need the applicable mountaineering/trekking permissions and must travel with an authorised operator. Allow time for paperwork and briefing.",
    permitOfficialLink: alpineClubLink,
    permitLastVerifiedAt: verifiedAt,
    roadCondition: "FOUR_WD_REQUIRED",
    avgVisitHours: 168,
    entryFeePkr: 0,
    safetyNotes:
      "A high-altitude, multi-day expedition requiring physical preparation, guides, insurance and contingency days for weather.",
    photos: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-biafo-glacier-trek",
    name: "Biafo Glacier Trek",
    slug: "biafo-glacier-trek",
    regionId: "region-skardu",
    category: "GLACIER",
    latitude: 35.9215,
    longitude: 75.8151,
    description:
      "A demanding multi-day glacier traverse from Askole toward Snow Lake, with wilderness logistics far beyond the paved road network.",
    bestSeasons: ["SUMMER"],
    altitudeMeters: 4300,
    requiresPermit: true,
    permitAuthority: "Alpine Club of Pakistan via a licensed trekking operator",
    permitNotes:
      "Confirm current permit and operator requirements before booking. This route should only be undertaken with an experienced, properly equipped team.",
    permitOfficialLink: alpineClubLink,
    permitLastVerifiedAt: verifiedAt,
    roadCondition: "FOUR_WD_REQUIRED",
    avgVisitHours: 192,
    entryFeePkr: 0,
    safetyNotes:
      "Glacier travel, river crossings and altitude demand expedition experience, guides, insurance and weather buffers.",
    photos: [
      "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },

  // Lahore
  {
    id: "poi-badshahi-mosque",
    name: "Badshahi Mosque",
    slug: "badshahi-mosque",
    regionId: "region-lahore",
    category: "MOSQUE",
    latitude: 31.5882,
    longitude: 74.3108,
    description:
      "Aurangzeb's monumental 17th-century mosque, a masterwork of red sandstone and marble beside Lahore Fort.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 217,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    safetyNotes:
      "Dress modestly, remove shoes before entering prayer areas and plan around Friday prayers and prayer times.",
    photos: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-lahore-fort",
    name: "Lahore Fort",
    slug: "lahore-fort",
    regionId: "region-lahore",
    category: "FORT",
    latitude: 31.5889,
    longitude: 74.3124,
    description:
      "A UNESCO-listed Mughal citadel with the Sheesh Mahal, Alamgiri Gate and layered architecture from several imperial eras.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2.5,
    entryFeePkr: 1000,
    photos: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-walled-city-delhi-gate",
    name: "Walled City & Delhi Gate",
    slug: "walled-city-delhi-gate",
    regionId: "region-lahore",
    category: "CITY_LANDMARK",
    latitude: 31.5807,
    longitude: 74.3165,
    description:
      "The dense historic core of Lahore: restored gates, rooftop views, havelis and lanes best understood on a guided walking tour.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 3,
    entryFeePkr: 0,
    safetyNotes:
      "Stay aware of traffic in narrow lanes and ask before photographing people or private spaces.",
    photos: [
      "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-shalimar-gardens",
    name: "Shalimar Gardens",
    slug: "shalimar-gardens",
    regionId: "region-lahore",
    category: "CITY_LANDMARK",
    latitude: 31.5858,
    longitude: 74.3814,
    description:
      "A formal Mughal garden of terraces, marble pavilions and water channels built for Emperor Shah Jahan.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 214,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 500,
    photos: [
      "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-wazir-khan-mosque",
    name: "Wazir Khan Mosque",
    slug: "wazir-khan-mosque",
    regionId: "region-lahore",
    category: "MOSQUE",
    latitude: 31.5825,
    longitude: 74.3235,
    description:
      "A jewel-box Mughal mosque famed for its intricate frescoes, tilework and calligraphy in the heart of the old city.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1,
    entryFeePkr: 0,
    safetyNotes:
      "This is an active religious site: dress modestly, remove shoes and keep visits respectful around prayers.",
    photos: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-data-darbar",
    name: "Data Darbar Shrine",
    slug: "data-darbar-shrine",
    regionId: "region-lahore",
    category: "SHRINE",
    latitude: 31.573,
    longitude: 74.3038,
    description:
      "The major Sufi shrine of Ali Hujwiri (Data Ganj Bakhsh), a living spiritual centre rather than simply a historic monument.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 214,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1,
    entryFeePkr: 0,
    safetyNotes:
      "Dress conservatively, avoid disruptive photography and be prepared for dense crowds, especially on Thursday evenings.",
    photos: [
      "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-anarkali-bazaar",
    name: "Anarkali Bazaar",
    slug: "anarkali-bazaar",
    regionId: "region-lahore",
    category: "BAZAAR",
    latitude: 31.5666,
    longitude: 74.3144,
    description:
      "One of South Asia's oldest surviving bazaars, full of fabrics, jewellery, street snacks and energetic evening trade.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 0,
    safetyNotes:
      "Keep valuables secure in crowded lanes and agree on prices before purchasing or taking a rickshaw.",
    photos: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-fort-road-food-street",
    name: "Fort Road Food Street",
    slug: "fort-road-food-street",
    regionId: "region-lahore",
    category: "RESTAURANT",
    latitude: 31.5875,
    longitude: 74.3111,
    description:
      "A cluster of rooftop and street-level restaurants near the fort, popular for Lahori classics and evening views of Badshahi Mosque.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-minar-e-pakistan",
    name: "Minar-e-Pakistan",
    slug: "minar-e-pakistan",
    regionId: "region-lahore",
    category: "CITY_LANDMARK",
    latitude: 31.5925,
    longitude: 74.3099,
    description:
      "The national monument in Iqbal Park marking the Lahore Resolution, within walking distance of the fort and mosque complex.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 216,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  // Swat Valley
  { id: "poi-swat-museum", name: "Swat Museum", slug: "swat-museum", regionId: "region-swat-valley", category: "MUSEUM", latitude: 34.767, longitude: 72.361, description: "Contains rich artifacts from the ancient Gandhara civilization.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN", "WINTER"], altitudeMeters: 980, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1.5, entryFeePkr: 500, photos: ["https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-mingora-bazaar", name: "Mingora Bazaar", slug: "mingora-bazaar", regionId: "region-swat-valley", category: "BAZAAR", latitude: 34.771, longitude: 72.360, description: "Bustling commercial hub of Swat, famous for local handicrafts and emeralds.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN", "WINTER"], altitudeMeters: 984, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-malam-jabba", name: "Malam Jabba Ski Resort", slug: "malam-jabba-ski-resort", regionId: "region-swat-valley", category: "HILL_STATION", latitude: 34.799, longitude: 72.572, description: "One of the few ski resorts in Pakistan offering stunning snowy landscapes.", bestSeasons: ["WINTER"], altitudeMeters: 2804, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 4, entryFeePkr: 1000, photos: ["https://images.unsplash.com/photo-1518779578993-ec3579fee39f?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-fizagat-park", name: "Fizagat Park", slug: "fizagat-park", regionId: "region-swat-valley", category: "VIEWPOINT", latitude: 34.789, longitude: 72.385, description: "A popular recreational park situated along the Swat River.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN"], altitudeMeters: 980, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 50, photos: ["https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-mahodand-lake", name: "Mahodand Lake", slug: "mahodand-lake", regionId: "region-swat-valley", category: "LAKE", latitude: 35.714, longitude: 72.650, description: "A scenic alpine lake accessible by a thrilling jeep ride from Kalam.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 2865, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 3, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-ushu-forest", name: "Ushu Forest", slug: "ushu-forest", regionId: "region-swat-valley", category: "VALLEY", latitude: 35.539, longitude: 72.593, description: "A dense pine forest offering picturesque walks in the Ushu valley.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 2300, requiresPermit: false, roadCondition: "UNPAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-swat-emerald-mines", name: "Swat Emerald Mines viewpoint", slug: "swat-emerald-mines-viewpoint", regionId: "region-swat-valley", category: "VIEWPOINT", latitude: 34.773, longitude: 72.367, description: "Viewpoint overlooking the historic emerald mines near Mingora.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN", "WINTER"], altitudeMeters: 1000, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },

  // Islamabad
  { id: "poi-faisal-mosque", name: "Faisal Mosque", slug: "faisal-mosque", regionId: "region-islamabad", category: "MOSQUE", latitude: 33.729, longitude: 73.037, description: "An iconic, modern mosque nestled at the foothills of the Margalla Hills.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 600, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1635016288720-c52507b9a717?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-margalla-trail-5", name: "Margalla Hills Trail 5", slug: "margalla-hills-trail-5", regionId: "region-islamabad", category: "NATIONAL_PARK", latitude: 33.738, longitude: 73.076, description: "A popular hiking trail with a freshwater stream.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 650, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 3, entryFeePkr: 0, photos: ["https://www.apricottours.pk/wp-content/uploads/2015/02/Margalla-Hills-Trail-5-Hiking-Tour-34.jpg"], source: "curated", verifiedAt },
  { id: "poi-pakistan-monument", name: "Pakistan Monument", slug: "pakistan-monument", regionId: "region-islamabad", category: "CITY_LANDMARK", latitude: 33.693, longitude: 73.068, description: "A blooming flower-shaped monument symbolizing the provinces of Pakistan.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 550, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1.5, entryFeePkr: 50, photos: ["https://images.unsplash.com/photo-1655841182960-d881381be362?auto=format&fit=crop&w=1800&q=85"], source: "curated", verifiedAt },
  { id: "poi-lok-virsa-museum", name: "Lok Virsa Museum", slug: "lok-virsa-museum", regionId: "region-islamabad", category: "MUSEUM", latitude: 33.685, longitude: 73.069, description: "Museum showcasing the cultural heritage of Pakistan.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 550, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 500, photos: ["https://chakorventures.com/wp-content/uploads/2025/11/IMG_0819-1024x682.jpg"], source: "curated", verifiedAt },
  { id: "poi-daman-e-koh", name: "Daman-e-Koh viewpoint", slug: "daman-e-koh-viewpoint", regionId: "region-islamabad", category: "VIEWPOINT", latitude: 33.739, longitude: 73.055, description: "A hilltop garden offering panoramic views of Islamabad.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 730, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://chakorventures.com/wp-content/uploads/2026/01/ambiance-compliments.jpg"], source: "curated", verifiedAt },
  { id: "poi-saidpur-village", name: "Saidpur Village", slug: "saidpur-village", regionId: "region-islamabad", category: "CITY_LANDMARK", latitude: 33.743, longitude: 73.067, description: "A restored historic Mughal-era village with charming cafes.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 620, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkw1STdKiGX9eapXPOTtdOtMBvbQ732l60zv9x2KZdpr-kzsOn6ALdkscJrfpXVLZdWrAxCG_H3OrlHc7rj33NH4Y29fHrydSX6iq4mNKfcyUztF9oFk01Qbm4LVlQIShR4AB1X=s1360-w1360-h1020-rw"], source: "curated", verifiedAt },
  { id: "poi-trail-3", name: "Trail 3 (Margalla)", slug: "trail-3-margalla", regionId: "region-islamabad", category: "NATIONAL_PARK", latitude: 33.733, longitude: 73.067, description: "A steep and challenging but highly rewarding hike in the Margalla Hills.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 650, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2.5, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },

  // Naran & Kaghan
  { id: "poi-saiful-malook", name: "Lake Saif-ul-Malook", slug: "lake-saif-ul-malook", regionId: "region-naran-kaghan", category: "LAKE", latitude: 34.873, longitude: 73.695, description: "A legendary alpine lake surrounded by snow-capped peaks.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 3224, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 3, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-lulusar-lake", name: "Lulusar Lake", slug: "lulusar-lake", regionId: "region-naran-kaghan", category: "LAKE", latitude: 35.083, longitude: 73.940, description: "The largest lake in the Kaghan Valley, reflecting the surrounding peaks.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 3410, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-babusar-pass", name: "Babusar Pass", slug: "babusar-pass", regionId: "region-naran-kaghan", category: "MOUNTAIN", latitude: 35.146, longitude: 74.045, description: "High mountain pass connecting Kaghan Valley to Gilgit-Baltistan.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 4173, requiresPermit: false, roadCondition: "SEASONAL_CLOSURE", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-naran-bazaar", name: "Naran Bazaar", slug: "naran-bazaar", regionId: "region-naran-kaghan", category: "BAZAAR", latitude: 34.908, longitude: 73.649, description: "The vibrant center of Naran, filled with local crafts and eateries.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 2409, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-lalazar", name: "Lalazar Plateau", slug: "lalazar-plateau", regionId: "region-naran-kaghan", category: "VIEWPOINT", latitude: 34.954, longitude: 73.715, description: "A beautiful meadow known for its wildflowers and views of Falak Sar.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 3200, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-ansoo-lake", name: "Ansoo Lake viewpoint", slug: "ansoo-lake-viewpoint", regionId: "region-naran-kaghan", category: "LAKE", latitude: 34.814, longitude: 73.676, description: "A teardrop-shaped high altitude lake reached by a challenging trek.", bestSeasons: ["SUMMER"], altitudeMeters: 4126, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 6, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-shogran", name: "Shogran Meadows", slug: "shogran-meadows", regionId: "region-naran-kaghan", category: "HILL_STATION", latitude: 34.624, longitude: 73.465, description: "A lush green plateau surrounded by thick pine forests.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 2362, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 3, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },

  // Peshawar
  { id: "poi-peshawar-museum", name: "Peshawar Museum", slug: "peshawar-museum", regionId: "region-peshawar", category: "MUSEUM", latitude: 34.007, longitude: 71.558, description: "Renowned for its collection of Gandharan art and Buddhist sculptures.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 331, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 500, photos: ["https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-qissa-khwani", name: "Qissa Khwani Bazaar", slug: "qissa-khwani-bazaar", regionId: "region-peshawar", category: "BAZAAR", latitude: 34.004, longitude: 71.572, description: "The famous Bazaar of Storytellers, rich in history and tea houses.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 331, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-bala-hisar", name: "Bala Hisar Fort", slug: "bala-hisar-fort", regionId: "region-peshawar", category: "FORT", latitude: 34.012, longitude: 71.568, description: "An imposing fort providing panoramic views of the city of Peshawar.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 331, requiresPermit: true, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-mahabat-khan", name: "Mahabat Khan Mosque", slug: "mahabat-khan-mosque", regionId: "region-peshawar", category: "MOSQUE", latitude: 34.006, longitude: 71.574, description: "A magnificent 17th-century Mughal mosque tucked away in the old city.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 331, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-gor-khatri", name: "Gor Khatri", slug: "gor-khatri", regionId: "region-peshawar", category: "ARCHAEOLOGICAL_SITE", latitude: 34.009, longitude: 71.581, description: "An ancient site holding layers of history from the Mauryan to Mughal eras.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 331, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1.5, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-old-city-walls", name: "Peshawar Old City Walls", slug: "peshawar-old-city-walls", regionId: "region-peshawar", category: "CITY_LANDMARK", latitude: 34.005, longitude: 71.578, description: "Remnants of the historic walled enclosures of ancient Peshawar.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 331, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },

  // Chitral & Kalash
  { id: "poi-kalash-valley", name: "Kalash Valley (Bumburet)", slug: "kalash-valley-bumburet", regionId: "region-chitral-kalash", category: "VALLEY", latitude: 35.683, longitude: 71.666, description: "The largest of the Kalash valleys, known for its unique culture and festivals.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN"], altitudeMeters: 1670, requiresPermit: true, roadCondition: "UNPAVED", avgVisitHours: 6, entryFeePkr: 1000, photos: ["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-chitral-fort", name: "Chitral Fort", slug: "chitral-fort", regionId: "region-chitral-kalash", category: "FORT", latitude: 35.851, longitude: 71.785, description: "Historical seat of the Mehtar of Chitral by the river.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN"], altitudeMeters: 1494, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://scontent.fisb1-2.fna.fbcdn.net/v/t1.6435-9/84170403_3103109089734554_1715535625945350144_n.jpg?stp=dst-jpg_tt6&cstp=mx2048x1364&ctp=p180x540&_nc_cat=104&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=833d8c&_nc_ohc=yuUzYbPvag0Q7kNvwE0yO0k&_nc_oc=Adql3By3IdpeWFCVbMSXOU5qkli6IyfgqTbl1-1GDafCrY2Rm5Y2sTqOUL4Fad89yUw&_nc_zt=23&_nc_ht=scontent.fisb1-2.fna&_nc_gid=W-TQCfPMGnFyw9xyTewUlw&_nc_ss=7a2a8&oh=00_AQG0H--c_ovDDXj3JcjJhrBZleQ7bRt0LmB83LWTTLp7gw&oe=6AB2F99D"], source: "curated", verifiedAt },
  { id: "poi-shandur-pass", name: "Shandur Pass", slug: "shandur-pass", regionId: "region-chitral-kalash", category: "MOUNTAIN", latitude: 36.082, longitude: 72.532, description: "Famous for the annual polo festival at the world's highest polo ground.", bestSeasons: ["SUMMER"], altitudeMeters: 3700, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 4, entryFeePkr: 0, photos: ["https://visitsilkroad.org/wp-content/uploads/2021/05/Shandur-Pass-Pakistan-1.jpg"], source: "curated", verifiedAt },
  { id: "poi-garam-chashma", name: "Garam Chashma Hot Springs", slug: "garam-chashma-hot-springs", regionId: "region-chitral-kalash", category: "VALLEY", latitude: 35.989, longitude: 71.439, description: "Therapeutic hot springs nestled in the Hindu Kush mountains.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN"], altitudeMeters: 1859, requiresPermit: false, roadCondition: "UNPAVED", avgVisitHours: 3, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-ayun-valley", name: "Ayun Valley", slug: "ayun-valley", regionId: "region-chitral-kalash", category: "VALLEY", latitude: 35.727, longitude: 71.777, description: "A lush green valley serving as the gateway to the Kalash valleys.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN"], altitudeMeters: 1400, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://media.licdn.com/dms/image/v2/C4D22AQEgsIZ37IRQ6w/feedshare-shrink_800/feedshare-shrink_800/0/1575878650513?e=1788998400&v=beta&t=qwbhyYDHwazmy2-KeNdNJIAdyjbF5sFUrwJjEdeQXzQ"], source: "curated", verifiedAt },
  { id: "poi-chitral-bazaar", name: "Chitral Bazaar", slug: "chitral-bazaar", regionId: "region-chitral-kalash", category: "BAZAAR", latitude: 35.852, longitude: 71.789, description: "Traditional market famous for Chitrali caps and handicrafts.", bestSeasons: ["SPRING", "SUMMER", "AUTUMN"], altitudeMeters: 1494, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://www.chitraltravel.com/images/shopping/6.jpg"], source: "curated", verifiedAt },

  // Fairy Meadows
  { id: "poi-fairy-meadows", name: "Fairy Meadows", slug: "fairy-meadows", regionId: "region-fairy-meadows-nanga-parbat", category: "VALLEY", latitude: 35.390, longitude: 74.577, description: "A breathtaking alpine pasture offering unparalleled views of Nanga Parbat.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 3300, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 24, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-nanga-parbat-bc", name: "Nanga Parbat Base Camp", slug: "nanga-parbat-base-camp", regionId: "region-fairy-meadows-nanga-parbat", category: "MOUNTAIN", latitude: 35.334, longitude: 74.582, description: "An achievable day trek from Fairy Meadows to the base of the Killer Mountain.", bestSeasons: ["SUMMER"], altitudeMeters: 3967, requiresPermit: false, roadCondition: "UNPAVED", avgVisitHours: 8, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-raikot-bridge", name: "Raikot Bridge viewpoint", slug: "raikot-bridge-viewpoint", regionId: "region-fairy-meadows-nanga-parbat", category: "VIEWPOINT", latitude: 35.485, longitude: 74.590, description: "The starting point for the legendary jeep track up to Fairy Meadows.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 1400, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-beyal-camp", name: "Beyal Camp", slug: "beyal-camp", regionId: "region-fairy-meadows-nanga-parbat", category: "VIEWPOINT", latitude: 35.361, longitude: 74.579, description: "A serene camping spot situated en route to the Nanga Parbat Base Camp.", bestSeasons: ["SUMMER"], altitudeMeters: 3500, requiresPermit: false, roadCondition: "UNPAVED", avgVisitHours: 3, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-tattoo-village", name: "Tattoo Village viewpoint", slug: "tattoo-village-viewpoint", regionId: "region-fairy-meadows-nanga-parbat", category: "VIEWPOINT", latitude: 35.426, longitude: 74.585, description: "The end of the jeep track and starting point of the hike to Fairy Meadows.", bestSeasons: ["SUMMER", "AUTUMN"], altitudeMeters: 2300, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-rupal-valley", name: "Rupal Valley", slug: "rupal-valley", regionId: "region-fairy-meadows-nanga-parbat", category: "VALLEY", latitude: 35.215, longitude: 74.622, description: "Stunning valley on the southern side of Nanga Parbat with massive rock walls.", bestSeasons: ["SUMMER"], altitudeMeters: 3000, requiresPermit: false, roadCondition: "FOUR_WD_REQUIRED", avgVisitHours: 12, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },

  // Multan
  { id: "poi-shah-rukn-e-alam", name: "Shrine of Shah Rukn-e-Alam", slug: "shrine-of-shah-rukn-e-alam", regionId: "region-multan", category: "SHRINE", latitude: 30.198, longitude: 71.472, description: "An iconic octagonal shrine celebrated for its stunning blue tilework.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 122, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1.5, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-multan-fort", name: "Multan Fort (Qila Kohna Qasim Bagh)", slug: "multan-fort", regionId: "region-multan", category: "FORT", latitude: 30.199, longitude: 71.472, description: "Remains of the ancient fort housing several prominent shrines.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 122, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-hussain-agahi", name: "Hussain Agahi Bazaar", slug: "hussain-agahi-bazaar", regionId: "region-multan", category: "BAZAAR", latitude: 30.196, longitude: 71.470, description: "One of Multan's oldest and busiest bazaars.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 122, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-shah-shams-tabriz", name: "Tomb of Shah Shams Tabriz", slug: "tomb-of-shah-shams-tabriz", regionId: "region-multan", category: "SHRINE", latitude: 30.207, longitude: 71.481, description: "A revered 14th-century tomb with exceptional glazed brickwork.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 122, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-multan-museum", name: "Multan Museum", slug: "multan-museum", regionId: "region-multan", category: "MUSEUM", latitude: 30.200, longitude: 71.472, description: "Exhibits artifacts from the region's long and varied history.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 122, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1.5, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-ghanta-ghar", name: "Ghanta Ghar Clock Tower", slug: "ghanta-ghar-clock-tower", regionId: "region-multan", category: "CITY_LANDMARK", latitude: 30.197, longitude: 71.470, description: "A British-era clock tower serving as the city center.", bestSeasons: ["SPRING", "AUTUMN", "WINTER"], altitudeMeters: 122, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 0.5, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },

  // Karachi
  { id: "poi-mazar-e-quaid", name: "Mazar-e-Quaid", slug: "mazar-e-quaid", regionId: "region-karachi", category: "CITY_LANDMARK", latitude: 24.8753, longitude: 67.0409, description: "The iconic white marble mausoleum and final resting place of Muhammad Ali Jinnah.", bestSeasons: ["AUTUMN", "WINTER", "SPRING"], altitudeMeters: 20, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1.5, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1759323050124-eb669cec0b72?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-clifton-beach", name: "Clifton Beach & Seaview", slug: "clifton-beach-seaview", regionId: "region-karachi", category: "VIEWPOINT", latitude: 24.7937, longitude: 67.0344, description: "Karachi's bustling Arabian Sea shoreline, famous for camel rides, sea breezes, and vibrant evening atmosphere.", bestSeasons: ["AUTUMN", "WINTER", "SPRING"], altitudeMeters: 0, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-mohatta-palace", name: "Mohatta Palace Museum", slug: "mohatta-palace-museum", regionId: "region-karachi", category: "MUSEUM", latitude: 24.8142, longitude: 67.0326, description: "A stunning 1927 Rajasthani-style stone palace showcasing Pakistani art, textiles, and cultural exhibits.", bestSeasons: ["AUTUMN", "WINTER", "SPRING"], altitudeMeters: 15, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 150, photos: ["https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-burns-road", name: "Burns Road Food Street", slug: "burns-road-food-street", regionId: "region-karachi", category: "RESTAURANT", latitude: 24.8582, longitude: 67.0145, description: "The historic epicentre of Karachi street food: Nihari, Haleem, kebabs, Rabri, and legacy eateries.", bestSeasons: ["AUTUMN", "WINTER", "SPRING"], altitudeMeters: 10, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-port-grand", name: "Port Grand", slug: "port-grand", regionId: "region-karachi", category: "CITY_LANDMARK", latitude: 24.8475, longitude: 66.9897, description: "A landscaped pedestrian food and entertainment promenade along the historic Native Jetty harbour.", bestSeasons: ["AUTUMN", "WINTER", "SPRING"], altitudeMeters: 5, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 2.5, entryFeePkr: 500, photos: ["https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt },
  { id: "poi-empress-market", name: "Empress Market", slug: "empress-market", regionId: "region-karachi", category: "BAZAAR", latitude: 24.8622, longitude: 67.0305, description: "A Victorian-era landmark market in Saddar, at the historical heart of colonial Karachi.", bestSeasons: ["AUTUMN", "WINTER", "SPRING"], altitudeMeters: 15, requiresPermit: false, roadCondition: "PAVED", avgVisitHours: 1.5, entryFeePkr: 0, photos: ["https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=85"], source: "curated", verifiedAt }
];
