import type { POI } from "@/lib/domain/types";

const verifiedAt = "2026-07-15T00:00:00.000Z";
const alpineClubLink = "https://www.alpineclub.org.pk/";

/**
 * Curated POIs are deliberately explicit rather than generated from a map API.
 * This is the grounding catalogue used by the mock itinerary generator.
 */
export const pois: POI[] = [
  // Hunza
  {
    id: "poi-attabad-lake",
    name: "Attabad Lake",
    slug: "attabad-lake",
    regionId: "region-hunza",
    category: "LAKE",
    latitude: 36.3257,
    longitude: 74.8727,
    description:
      "A striking turquoise lake formed after the 2010 Attabad landslide. Take a boat ride, then pause at the tunnel viewpoints along the Karakoram Highway.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2560,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 0,
    safetyNotes:
      "Wear a buoyancy aid for boat trips and ask locally about wind conditions before going out on the water.",
    photos: [
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-baltit-fort",
    name: "Baltit Fort",
    slug: "baltit-fort",
    regionId: "region-hunza",
    category: "FORT",
    latitude: 36.3243,
    longitude: 74.6679,
    description:
      "A 700-year-old fort above Karimabad, restored as a museum of Hunza's royal history, timber craftsmanship and mountain trade routes.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2500,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 1200,
    photos: [
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-altit-fort",
    name: "Altit Fort",
    slug: "altit-fort",
    regionId: "region-hunza",
    category: "FORT",
    latitude: 36.3225,
    longitude: 74.6944,
    description:
      "Hunza's older royal fort, paired with the carefully restored Altit village and its terraced gardens above the Hunza River.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2500,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 1000,
    photos: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-eagles-nest-duikar",
    name: "Eagle's Nest, Duikar",
    slug: "eagles-nest-duikar",
    regionId: "region-hunza",
    category: "VIEWPOINT",
    latitude: 36.3284,
    longitude: 74.6545,
    description:
      "A high lookout above Karimabad known for broad sunrise and sunset views across the Hunza and Nagar valleys.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2850,
    requiresPermit: false,
    roadCondition: "UNPAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    safetyNotes:
      "The final climb is steep and narrow. Use a local driver after dark and carry a warm layer even in summer.",
    photos: [
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-passu-cones",
    name: "Passu Cones Viewpoint",
    slug: "passu-cones-viewpoint",
    regionId: "region-hunza",
    category: "MOUNTAIN",
    latitude: 36.4621,
    longitude: 74.8923,
    description:
      "A roadside view to the cathedral-like Passu Cones and the glacier valley beyond; light is especially good early and late in the day.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2550,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-hussaini-bridge",
    name: "Hussaini Suspension Bridge",
    slug: "hussaini-suspension-bridge",
    regionId: "region-hunza",
    category: "VIEWPOINT",
    latitude: 36.456,
    longitude: 74.8933,
    description:
      "A long plank-and-cable suspension bridge over the Hunza River near Hussaini village, best approached calmly and with sensible footwear.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2540,
    requiresPermit: false,
    roadCondition: "UNPAVED",
    avgVisitHours: 1,
    entryFeePkr: 500,
    safetyNotes:
      "Cross only when the bridge is open and conditions are calm. It is not suitable for anyone uncomfortable with exposed heights.",
    photos: [
      "https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-khunjerab-pass",
    name: "Khunjerab Pass",
    slug: "khunjerab-pass",
    regionId: "region-hunza",
    category: "MOUNTAIN",
    latitude: 36.8508,
    longitude: 75.4306,
    description:
      "The high Pakistan–China border crossing at the top of the Karakoram Highway, with dramatic open plateau scenery and severe altitude.",
    bestSeasons: ["SUMMER", "AUTUMN"],
    altitudeMeters: 4693,
    requiresPermit: false,
    roadCondition: "SEASONAL_CLOSURE",
    avgVisitHours: 4,
    entryFeePkr: 0,
    safetyNotes:
      "The road typically closes with winter snow. Go only after checking current official/local road status; altitude symptoms are common at this height.",
    photos: [
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-kilik-mintaka-trek",
    name: "Kilik & Mintaka Pass Trek",
    slug: "kilik-mintaka-pass-trek",
    regionId: "region-hunza",
    category: "MOUNTAIN",
    latitude: 36.9587,
    longitude: 74.6746,
    description:
      "A remote high-altitude trek in upper Chapursan toward historic Silk Road passes near the Afghan and Chinese border areas.",
    bestSeasons: ["SUMMER"],
    altitudeMeters: 4700,
    requiresPermit: true,
    permitAuthority: "Gilgit-Baltistan local administration and licensed trekking operator",
    permitNotes:
      "Border-zone access is controlled. Foreign and independent travelers should arrange clearance and a qualified local operator before committing transport or trekking days.",
    permitOfficialLink: alpineClubLink,
    permitLastVerifiedAt: verifiedAt,
    roadCondition: "FOUR_WD_REQUIRED",
    avgVisitHours: 8,
    entryFeePkr: 0,
    safetyNotes:
      "High altitude, sparse services and changing border-area rules make this an expedition-style activity, not a casual day trip.",
    photos: [
      "https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },

  // Skardu
  {
    id: "poi-shangrila-lake",
    name: "Lower Kachura Lake (Shangrila)",
    slug: "lower-kachura-lake-shangrila",
    regionId: "region-skardu",
    category: "LAKE",
    latitude: 35.2857,
    longitude: 75.6298,
    description:
      "A calm lake south of Skardu framed by poplars and steep brown mountains, with easy paths and classic first-day scenery.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2500,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 1500,
    photos: [
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-upper-kachura-lake",
    name: "Upper Kachura Lake",
    slug: "upper-kachura-lake",
    regionId: "region-skardu",
    category: "LAKE",
    latitude: 35.285,
    longitude: 75.6567,
    description:
      "A clearer, quieter lake beyond Lower Kachura, reached by a short rough approach and ideal for an unhurried lakeside afternoon.",
    bestSeasons: ["SUMMER", "AUTUMN"],
    altitudeMeters: 2500,
    requiresPermit: false,
    roadCondition: "UNPAVED",
    avgVisitHours: 2.5,
    entryFeePkr: 500,
    photos: [
      "https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-shigar-fort",
    name: "Shigar Fort",
    slug: "shigar-fort",
    regionId: "region-skardu",
    category: "FORT",
    latitude: 35.4216,
    longitude: 75.7349,
    description:
      "A 17th-century Balti fort and museum restored in the Shigar Valley, with a beautiful old village walk around it.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2230,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 1000,
    photos: [
      "https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-deosai-plains",
    name: "Deosai Plains",
    slug: "deosai-plains",
    regionId: "region-skardu",
    category: "NATIONAL_PARK",
    latitude: 35.0301,
    longitude: 75.4285,
    description:
      "A vast high plateau of wildflowers, streams and brown-bear habitat, often called the Roof of the World.",
    bestSeasons: ["SUMMER"],
    altitudeMeters: 4114,
    requiresPermit: false,
    roadCondition: "SEASONAL_CLOSURE",
    avgVisitHours: 7,
    entryFeePkr: 1000,
    safetyNotes:
      "Open roughly June to September only. Bring warm layers, sun protection, water and enough time to acclimatise to the altitude.",
    photos: [
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-manthoka-waterfall",
    name: "Manthoka Waterfall",
    slug: "manthoka-waterfall",
    regionId: "region-skardu",
    category: "WATERFALL",
    latitude: 35.5158,
    longitude: 75.9742,
    description:
      "A broad, cold waterfall in Kharmang District, surrounded by cultivated fields and a popular summer picnic area.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 1800,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 300,
    photos: [
      "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-basho-valley",
    name: "Basho Valley",
    slug: "basho-valley",
    regionId: "region-skardu",
    category: "VALLEY",
    latitude: 35.4224,
    longitude: 75.9907,
    description:
      "A green side valley of pine forests, river crossings and open meadows east of Skardu, rewarding a full jeep day.",
    bestSeasons: ["SUMMER", "AUTUMN"],
    altitudeMeters: 2900,
    requiresPermit: false,
    roadCondition: "FOUR_WD_REQUIRED",
    avgVisitHours: 7,
    entryFeePkr: 0,
    safetyNotes:
      "Use an experienced local 4x4 driver; road surfaces and stream crossings change with weather.",
    photos: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-katpana-desert",
    name: "Katpana Cold Desert",
    slug: "katpana-cold-desert",
    regionId: "region-skardu",
    category: "VIEWPOINT",
    latitude: 35.3091,
    longitude: 75.6048,
    description:
      "Silver sand dunes edged by snow-lined mountains just outside Skardu, particularly atmospheric near sunrise and sunset.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2226,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-satpara-lake",
    name: "Satpara Lake",
    slug: "satpara-lake",
    regionId: "region-skardu",
    category: "LAKE",
    latitude: 35.2234,
    longitude: 75.6696,
    description:
      "A deep blue reservoir beneath the Deosai approach, with a mountain backdrop and convenient stops from Skardu town.",
    bestSeasons: ["SPRING", "SUMMER", "AUTUMN"],
    altitudeMeters: 2636,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-k2-concordia-trek",
    name: "K2 Base Camp & Concordia Trek",
    slug: "k2-base-camp-concordia-trek",
    regionId: "region-skardu",
    category: "GLACIER",
    latitude: 35.8803,
    longitude: 76.5141,
    description:
      "Pakistan's iconic multi-day Baltoro Glacier expedition to Concordia and the base of K2; this is not a day excursion from Skardu.",
    bestSeasons: ["SUMMER"],
    altitudeMeters: 5000,
    requiresPermit: true,
    permitAuthority: "Alpine Club of Pakistan via a licensed trekking operator",
    permitNotes:
      "Foreign trekkers need the applicable mountaineering/trekking permissions and must travel with an authorised operator. Allow time for paperwork and briefing.",
    permitOfficialLink: alpineClubLink,
    permitLastVerifiedAt: verifiedAt,
    roadCondition: "FOUR_WD_REQUIRED",
    avgVisitHours: 168,
    entryFeePkr: 0,
    safetyNotes:
      "A high-altitude, multi-day expedition requiring physical preparation, guides, insurance and contingency days for weather.",
    photos: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },
  {
    id: "poi-biafo-glacier-trek",
    name: "Biafo Glacier Trek",
    slug: "biafo-glacier-trek",
    regionId: "region-skardu",
    category: "GLACIER",
    latitude: 35.9215,
    longitude: 75.8151,
    description:
      "A demanding multi-day glacier traverse from Askole toward Snow Lake, with wilderness logistics far beyond the paved road network.",
    bestSeasons: ["SUMMER"],
    altitudeMeters: 4300,
    requiresPermit: true,
    permitAuthority: "Alpine Club of Pakistan via a licensed trekking operator",
    permitNotes:
      "Confirm current permit and operator requirements before booking. This route should only be undertaken with an experienced, properly equipped team.",
    permitOfficialLink: alpineClubLink,
    permitLastVerifiedAt: verifiedAt,
    roadCondition: "FOUR_WD_REQUIRED",
    avgVisitHours: 192,
    entryFeePkr: 0,
    safetyNotes:
      "Glacier travel, river crossings and altitude demand expedition experience, guides, insurance and weather buffers.",
    photos: [
      "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "curated",
    verifiedAt,
  },

  // Lahore
  {
    id: "poi-badshahi-mosque",
    name: "Badshahi Mosque",
    slug: "badshahi-mosque",
    regionId: "region-lahore",
    category: "MOSQUE",
    latitude: 31.5882,
    longitude: 74.3108,
    description:
      "Aurangzeb's monumental 17th-century mosque, a masterwork of red sandstone and marble beside Lahore Fort.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 217,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    safetyNotes:
      "Dress modestly, remove shoes before entering prayer areas and plan around Friday prayers and prayer times.",
    photos: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-lahore-fort",
    name: "Lahore Fort",
    slug: "lahore-fort",
    regionId: "region-lahore",
    category: "FORT",
    latitude: 31.5889,
    longitude: 74.3124,
    description:
      "A UNESCO-listed Mughal citadel with the Sheesh Mahal, Alamgiri Gate and layered architecture from several imperial eras.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2.5,
    entryFeePkr: 1000,
    photos: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-walled-city-delhi-gate",
    name: "Walled City & Delhi Gate",
    slug: "walled-city-delhi-gate",
    regionId: "region-lahore",
    category: "CITY_LANDMARK",
    latitude: 31.5807,
    longitude: 74.3165,
    description:
      "The dense historic core of Lahore: restored gates, rooftop views, havelis and lanes best understood on a guided walking tour.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 3,
    entryFeePkr: 0,
    safetyNotes:
      "Stay aware of traffic in narrow lanes and ask before photographing people or private spaces.",
    photos: [
      "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-shalimar-gardens",
    name: "Shalimar Gardens",
    slug: "shalimar-gardens",
    regionId: "region-lahore",
    category: "CITY_LANDMARK",
    latitude: 31.5858,
    longitude: 74.3814,
    description:
      "A formal Mughal garden of terraces, marble pavilions and water channels built for Emperor Shah Jahan.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 214,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 500,
    photos: [
      "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-wazir-khan-mosque",
    name: "Wazir Khan Mosque",
    slug: "wazir-khan-mosque",
    regionId: "region-lahore",
    category: "MOSQUE",
    latitude: 31.5825,
    longitude: 74.3235,
    description:
      "A jewel-box Mughal mosque famed for its intricate frescoes, tilework and calligraphy in the heart of the old city.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1,
    entryFeePkr: 0,
    safetyNotes:
      "This is an active religious site: dress modestly, remove shoes and keep visits respectful around prayers.",
    photos: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-data-darbar",
    name: "Data Darbar Shrine",
    slug: "data-darbar-shrine",
    regionId: "region-lahore",
    category: "SHRINE",
    latitude: 31.573,
    longitude: 74.3038,
    description:
      "The major Sufi shrine of Ali Hujwiri (Data Ganj Bakhsh), a living spiritual centre rather than simply a historic monument.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 214,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1,
    entryFeePkr: 0,
    safetyNotes:
      "Dress conservatively, avoid disruptive photography and be prepared for dense crowds, especially on Thursday evenings.",
    photos: [
      "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-anarkali-bazaar",
    name: "Anarkali Bazaar",
    slug: "anarkali-bazaar",
    regionId: "region-lahore",
    category: "BAZAAR",
    latitude: 31.5666,
    longitude: 74.3144,
    description:
      "One of South Asia's oldest surviving bazaars, full of fabrics, jewellery, street snacks and energetic evening trade.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 2,
    entryFeePkr: 0,
    safetyNotes:
      "Keep valuables secure in crowded lanes and agree on prices before purchasing or taking a rickshaw.",
    photos: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-fort-road-food-street",
    name: "Fort Road Food Street",
    slug: "fort-road-food-street",
    regionId: "region-lahore",
    category: "RESTAURANT",
    latitude: 31.5875,
    longitude: 74.3111,
    description:
      "A cluster of rooftop and street-level restaurants near the fort, popular for Lahori classics and evening views of Badshahi Mosque.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 215,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1.5,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
  {
    id: "poi-minar-e-pakistan",
    name: "Minar-e-Pakistan",
    slug: "minar-e-pakistan",
    regionId: "region-lahore",
    category: "CITY_LANDMARK",
    latitude: 31.5925,
    longitude: 74.3099,
    description:
      "The national monument in Iqbal Park marking the Lahore Resolution, within walking distance of the fort and mosque complex.",
    bestSeasons: ["SPRING", "AUTUMN", "WINTER"],
    altitudeMeters: 216,
    requiresPermit: false,
    roadCondition: "PAVED",
    avgVisitHours: 1,
    entryFeePkr: 0,
    photos: [
      "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1400&q=85",
    ],
    source: "google_places",
    verifiedAt,
  },
];
