import type { ChatMessage, Trip } from "@/lib/domain/types";
import { mockUser } from "./users";

const owner = {
  id: mockUser.id,
  name: mockUser.name,
  email: mockUser.email,
  avatarUrl: mockUser.avatarUrl,
};

/** A complete first-load itinerary so the product never opens to an empty state. */
export const sampleHunzaTrip: Trip = {
  id: "trip-hunza-summer-route",
  ownerId: mockUser.id,
  owner,
  title: "Hunza, slowly",
  slug: "hunza-slowly-july-2026",
  startDate: "2026-07-14T00:00:00.000Z",
  endDate: "2026-07-18T00:00:00.000Z",
  travelerType: "FRIENDS",
  budgetTier: "MID_RANGE",
  pace: "balanced",
  status: "CONFIRMED",
  coverImageUrl:
    "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=85",
  isPublic: true,
  shareToken: "hunza-summer-route",
  partySize: 4,
  vibe: "Scenic drives, gentle walks, heritage and unhurried mountain meals.",
  createdAt: "2026-05-25T09:45:00.000Z",
  updatedAt: "2026-07-13T15:20:00.000Z",
  collaborators: [
    {
      id: "collaborator-sana-owner",
      tripId: "trip-hunza-summer-route",
      userId: mockUser.id,
      user: owner,
      role: "OWNER",
      joinedAt: "2026-05-25T09:45:00.000Z",
      createdAt: "2026-05-25T09:45:00.000Z",
    },
    {
      id: "collaborator-hamza-editor",
      tripId: "trip-hunza-summer-route",
      userId: "user-hamza-ali",
      user: {
        id: "user-hamza-ali",
        name: "Hamza Ali",
        email: "hamza@example.com",
        avatarUrl: null,
      },
      role: "EDITOR",
      joinedAt: "2026-05-26T12:00:00.000Z",
      createdAt: "2026-05-25T11:00:00.000Z",
    },
  ],
  days: [
    {
      id: "day-hunza-1",
      tripId: "trip-hunza-summer-route",
      dayNumber: 1,
      date: "2026-07-14T00:00:00.000Z",
      regionId: "region-hunza",
      notes:
        "Arrive gently. Keep the first day flexible for road delays and spend the evening in Altit village rather than overfilling it.",
      activities: [
        {
          id: "activity-hunza-1-transfer",
          tripDayId: "day-hunza-1",
          poiId: null,
          customTitle: "Private transfer into Karimabad via the Karakoram Highway",
          category: "TRANSPORT",
          startTime: "09:00",
          endTime: "15:30",
          orderIndex: 0,
          notes: "Pause for meals and road-condition checks; actual timings vary with the route you start from.",
          estimatedCost: 18000,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
        {
          id: "activity-hunza-1-altit",
          tripDayId: "day-hunza-1",
          poiId: "poi-altit-fort",
          customTitle: null,
          category: "SIGHTSEEING",
          startTime: "16:30",
          endTime: "18:00",
          orderIndex: 1,
          notes: "A calm first heritage stop after the drive.",
          estimatedCost: 1000,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
        {
          id: "activity-hunza-1-lodging",
          tripDayId: "day-hunza-1",
          poiId: null,
          customTitle: "Check in and rooftop dinner in Karimabad",
          category: "LODGING",
          startTime: "19:00",
          endTime: "20:30",
          orderIndex: 2,
          notes: "Ask your host about sunrise visibility and the next day's road conditions.",
          estimatedCost: 8500,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
      ],
    },
    {
      id: "day-hunza-2",
      tripId: "trip-hunza-summer-route",
      dayNumber: 2,
      date: "2026-07-15T00:00:00.000Z",
      regionId: "region-hunza",
      notes:
        "A local Karimabad day with time to walk, snack and rest rather than treating the forts as a checklist.",
      activities: [
        {
          id: "activity-hunza-2-baltit",
          tripDayId: "day-hunza-2",
          poiId: "poi-baltit-fort",
          customTitle: null,
          category: "SIGHTSEEING",
          startTime: "09:00",
          endTime: "10:30",
          orderIndex: 0,
          notes: "Join a guide if one is available for the fort's history and restoration story.",
          estimatedCost: 1200,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
        {
          id: "activity-hunza-2-bazaar",
          tripDayId: "day-hunza-2",
          poiId: null,
          customTitle: "Karimabad bazaar lunch and apricot shopping",
          category: "SHOPPING",
          startTime: "12:00",
          endTime: "14:00",
          orderIndex: 1,
          notes: "Keep cash for small purchases and try local apricot products.",
          estimatedCost: 2500,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
        {
          id: "activity-hunza-2-eagles-nest",
          tripDayId: "day-hunza-2",
          poiId: "poi-eagles-nest-duikar",
          customTitle: null,
          category: "SIGHTSEEING",
          startTime: "17:00",
          endTime: "19:00",
          orderIndex: 2,
          notes: "Sunset is lovely, but take a warm layer and arrange the return driver before dark.",
          estimatedCost: 3000,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
      ],
    },
    {
      id: "day-hunza-3",
      tripId: "trip-hunza-summer-route",
      dayNumber: 3,
      date: "2026-07-16T00:00:00.000Z",
      regionId: "region-hunza",
      notes:
        "Drive north with room for spontaneous viewpoints. Keep this day loose—the lake and Passu deserve more than quick photo stops.",
      activities: [
        {
          id: "activity-hunza-3-attabad",
          tripDayId: "day-hunza-3",
          poiId: "poi-attabad-lake",
          customTitle: null,
          category: "ADVENTURE",
          startTime: "09:00",
          endTime: "11:30",
          orderIndex: 0,
          notes: "Boat ride if wind conditions are suitable; wear the provided buoyancy aid.",
          estimatedCost: 3500,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
        {
          id: "activity-hunza-3-hussaini",
          tripDayId: "day-hunza-3",
          poiId: "poi-hussaini-bridge",
          customTitle: null,
          category: "SIGHTSEEING",
          startTime: "13:00",
          endTime: "14:00",
          orderIndex: 1,
          notes: "Optional crossing—enjoy the viewpoint instead if heights are not your thing.",
          estimatedCost: 500,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
        {
          id: "activity-hunza-3-passu",
          tripDayId: "day-hunza-3",
          poiId: "poi-passu-cones",
          customTitle: null,
          category: "SIGHTSEEING",
          startTime: "16:30",
          endTime: "17:30",
          orderIndex: 2,
          notes: "Catch the last light on the cones before checking into Passu.",
          estimatedCost: 0,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
      ],
    },
    {
      id: "day-hunza-4",
      tripId: "trip-hunza-summer-route",
      dayNumber: 4,
      date: "2026-07-17T00:00:00.000Z",
      regionId: "region-hunza",
      notes:
        "An intentionally early high-altitude day. This leg stays provisional until the border and road opening are confirmed locally.",
      activities: [
        {
          id: "activity-hunza-4-khunjerab",
          tripDayId: "day-hunza-4",
          poiId: "poi-khunjerab-pass",
          customTitle: null,
          category: "ADVENTURE",
          startTime: "07:00",
          endTime: "15:00",
          orderIndex: 0,
          notes: "Carry water, sun protection and warm layers. Turn around if anyone develops altitude symptoms.",
          estimatedCost: 15000,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
        {
          id: "activity-hunza-4-rest",
          tripDayId: "day-hunza-4",
          poiId: null,
          customTitle: "Rest and dinner in Passu",
          category: "REST",
          startTime: "18:30",
          endTime: "20:00",
          orderIndex: 1,
          notes: "An early night after a long road day.",
          estimatedCost: 2500,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
      ],
    },
    {
      id: "day-hunza-5",
      tripId: "trip-hunza-summer-route",
      dayNumber: 5,
      date: "2026-07-18T00:00:00.000Z",
      regionId: "region-hunza",
      notes:
        "A deliberately flexible southbound day—keep it as a weather/road buffer instead of adding another must-see stop.",
      activities: [
        {
          id: "activity-hunza-5-return",
          tripDayId: "day-hunza-5",
          poiId: null,
          customTitle: "Karakoram Highway return and flexible buffer",
          category: "TRANSPORT",
          startTime: "09:00",
          endTime: "16:00",
          orderIndex: 0,
          notes: "Use a portion of this buffer if mountain weather delayed an earlier activity.",
          estimatedCost: 18000,
          costCurrency: "PKR",
          addedByUserId: mockUser.id,
        },
      ],
    },
  ],
};

export const sampleTrips: Trip[] = [sampleHunzaTrip];

export const sampleChatMessages: ChatMessage[] = [
  {
    id: "chat-hunza-brief",
    tripId: sampleHunzaTrip.id,
    role: "user",
    content:
      "We are four friends who want scenic drives, gentle walks and historic places. Keep the pace balanced and leave a weather buffer.",
    createdAt: "2026-05-25T09:47:00.000Z",
  },
  {
    id: "chat-hunza-assistant",
    tripId: sampleHunzaTrip.id,
    role: "assistant",
    content:
      "I built a five-day Hunza route with a deliberately flexible final day. Khunjerab is marked as conditional on current road and border status.",
    createdAt: "2026-05-25T09:47:12.000Z",
  },
];
