import Link from "next/link";
import { ArrowRight, BadgeCheck, MapPinned, ShieldCheck, Sparkles } from "lucide-react";
import type { Region, TripTemplate } from "@/lib/domain/types";
import { HeroTripPrompt } from "@/components/marketing/hero-trip-prompt";
import { DestinationCard } from "@/components/marketing/destination-card";
import { TemplateCard } from "@/components/templates/template-card";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/ui/section-heading";

export function LandingPage({ regions, templates }: { regions: Region[]; templates: TripTemplate[] }) {
  return <>
    <section className="relative isolate overflow-hidden bg-karakoram-ink px-4 pb-20 pt-16 text-sandstone-mist sm:px-6 sm:pb-28 sm:pt-24 lg:px-8">
      <div aria-hidden="true" className="lattice pointer-events-none absolute inset-y-0 right-0 z-[-1] hidden w-[34%] opacity-60 [mask-image:linear-gradient(to_right,transparent,black_25%)] [-webkit-mask-image:linear-gradient(to_right,transparent,black_25%)] xl:block" />
      <div aria-hidden="true" className="pointer-events-none absolute inset-x-0 bottom-0 z-[-1] h-48 bg-gradient-to-t from-black/30 to-transparent" />
      <div className="mx-auto max-w-7xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-truck-art-marigold/30 bg-truck-art-marigold/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-truck-art-marigold"><Sparkles size={14} /> Pakistan, made personal</p><h1 className="display-type max-w-3xl text-5xl leading-[.93] tracking-tight sm:text-6xl lg:text-6xl">A better way to find <em className="font-normal text-truck-art-marigold">your</em> Pakistan.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-sandstone-mist/75 sm:text-lg">Tell us the shape of your journey. Safar turns real places, road knowledge and seasonal context into a plan you can actually take.</p><HeroTripPrompt /><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-sandstone-mist/74"><span className="inline-flex items-center gap-2"><BadgeCheck className="text-truck-art-marigold" size={17} /> Verified places, not guesses</span><span className="inline-flex items-center gap-2"><ShieldCheck className="text-truck-art-marigold" size={17} /> Permit & season aware</span><span className="inline-flex items-center gap-2"><MapPinned className="text-truck-art-marigold" size={17} /> Built for Pakistan</span></div></div>
    </section>
    <section className="paper-grain px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading eyebrow="Start somewhere remarkable" title="Pick a place. We’ll help with the rest." description="From mountain passes to Mughal courtyards, every route begins with a known place and local context." /><Button asChild variant="secondary"><Link href="/destinations">All destinations <ArrowRight size={16} /></Link></Button></div><div className="mt-10 grid gap-5 md:grid-cols-3">{regions.map((region, index) => <DestinationCard key={region.id} region={region} index={index} />)}</div></div></section>
    <section className="bg-white px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading eyebrow="Curated escapes" title="A good first draft, already made." description="Realistic itineraries built around the way Pakistan moves — room for mountain weather, tea breaks and the long way round." /><Button asChild variant="ghost"><Link href="/templates">See all escapes <ArrowRight size={16} /></Link></Button></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{templates.map((template) => <TemplateCard key={template.id} template={template} />)}</div></div></section>
    <section className="relative overflow-hidden bg-karakoram-ink px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="absolute inset-y-0 right-0 hidden w-1/2 bg-[radial-gradient(ellipse_at_center,_rgba(28,130,153,.28),_transparent_65%)] md:block" /><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><SectionHeading inverted eyebrow="Grounded by design" title="It’s an AI that knows when to slow down." description="Safar only works with a curated place database. It explains seasonality, road conditions and permits as part of the plan — not an afterthought." /><div className="grid gap-3"><div className="rounded-2xl border border-white/14 bg-white/[.04] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-truck-art-marigold">01 · Real places</p><p className="mt-2 text-sm leading-6 text-sandstone-mist">Every stop is selected from our Pakistan travel database, so your plan starts with ground truth.</p></div><div className="rounded-2xl border border-white/14 bg-white/[.04] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-truck-art-marigold">02 · Local context</p><p className="mt-2 text-sm leading-6 text-sandstone-mist">Road notes, altitude and seasonal fit surface exactly when a decision needs them.</p></div><div className="rounded-2xl border border-white/14 bg-white/[.04] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-truck-art-marigold">03 · Your route</p><p className="mt-2 text-sm leading-6 text-sandstone-mist">Refine the plan in conversation, share it with your people, then take it at your own pace.</p></div></div></div></section>
  </>;
}