import Link from "next/link";
import { ArrowRight, CalendarDays, CircleAlert, Compass, MapPin } from "lucide-react";
import type { POI, Region, TripTemplate } from "@/lib/domain/types";
import { PageHero } from "@/components/layout/page-hero";
import { PoiCard } from "@/components/pois/poi-card";
import { TemplateCard } from "@/components/templates/template-card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/ui/section-heading";

export function DestinationDetail({ region, pois, templates }: { region: Region; pois: POI[]; templates: TripTemplate[] }) {
  return <><PageHero eyebrow={`${region.province} · Pakistan`} title={region.name} description={region.description ?? "A starting point for a memorable journey."} className="bg-cover bg-center" >
    <div className="mt-7 flex flex-wrap gap-2"><Badge variant="marigold"><CalendarDays size={13} /> Best: {region.bestSeasons.map((season) => season[0] + season.slice(1).toLowerCase()).join(" · ")}</Badge><Badge variant="marigold"><MapPin size={13} /> {region.typicalTripDays ?? 3} days</Badge></div><Button asChild className="mt-7" variant="light"><Link href={`/trips/new?destination=${region.slug}`}>Plan a {region.name} trip <ArrowRight size={16} /></Link></Button>
  </PageHero><section className="bg-sandstone-mist px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-3"><div className="rounded-2xl border border-karakoram-ink/10 bg-white p-5"><Compass className="text-attabad-turquoise" size={22} /><h2 className="mt-4 font-bold">Planning note</h2><p className="mt-2 text-sm leading-6 text-karakoram-ink/70">{region.planningNotes ?? "Travel conditions can change; build in a little room for the road."}</p></div><div className="rounded-2xl border border-karakoram-ink/10 bg-white p-5"><CalendarDays className="text-truck-art-marigold" size={22} /><h2 className="mt-4 font-bold">Season matters</h2><p className="mt-2 text-sm leading-6 text-karakoram-ink/70">Safar uses the trip dates you enter to flag a seasonal mismatch before you leave.</p></div><div className="rounded-2xl border border-karakoram-ink/10 bg-white p-5"><CircleAlert className="text-alert-red" size={22} /><h2 className="mt-4 font-bold">Travel carefully</h2><p className="mt-2 text-sm leading-6 text-karakoram-ink/70">Road access, permits and safety notes are advisory. Verify current conditions locally.</p></div></div></section><section className="bg-white px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Verified places" title={`Get to know ${region.name}.`} description="A practical place database — not a list of things we hope are still open." /><div className="mt-10 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{pois.map((poi) => <PoiCard key={poi.id} poi={poi} />)}</div></div></section>{templates.length > 0 && <section className="paper-grain px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="A clear first step" title={`Routes through ${region.name}.`} /><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{templates.map((template) => <TemplateCard key={template.id} template={template} />)}</div></div></section>}</>;
}
