import Link from "next/link";
import { ArrowRight, CalendarDays, ChevronRight, Compass, Plus, Share2, Sparkles } from "lucide-react";
import type { Trip } from "@/lib/domain/types";
import { PageHero } from "@/components/layout/page-hero";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

function range(trip: Trip) { const formatter = new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }); return `${formatter.format(new Date(trip.startDate))} – ${formatter.format(new Date(trip.endDate))}`; }

export function TripsDashboard({ trips }: { trips: Trip[] }) {
  const live = trips.filter((trip) => trip.status !== "ARCHIVED");
  return <><PageHero eyebrow="Your travel notebook" title="Trips, in the making." description="Your Safar routes live here. Return to refine, share, or pick up the next good idea."><Button asChild className="mt-8" variant="light"><Link href="/trips/new"><Plus size={16} /> Plan a trip</Link></Button></PageHero><section className="paper-grain min-h-[50vh] px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-7 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-truck-art-marigold">Your routes</p><h2 className="display-type mt-2 text-4xl">Ready when you are.</h2></div><p className="text-sm text-karakoram-ink/60">{live.length} saved route{live.length === 1 ? "" : "s"}</p></div>{live.length === 0 ? <div className="rounded-[1.5rem] border border-karakoram-ink/12 bg-white p-10 text-center"><Compass className="mx-auto text-attabad-turquoise" size={32} /><h3 className="display-type mt-4 text-3xl">The map is wide open.</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-karakoram-ink/68">Start with a few details and Safar will sketch a first route based on real, verified places.</p><Button asChild className="mt-6"><Link href="/trips/new">Start a trip <ArrowRight size={16} /></Link></Button></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{live.map((trip) => <Link key={trip.id} href={`/trips/${trip.id}`} className="group relative overflow-hidden rounded-[1.4rem] border border-karakoram-ink/12 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-route-card"><div className="absolute inset-0 -z-10 bg-cover bg-center opacity-[.12]" style={{ backgroundImage: trip.coverImageUrl ? `url(${trip.coverImageUrl})` : undefined }} /><div className="flex items-start justify-between gap-3"><Badge variant={trip.status === "CONFIRMED" ? "meadow" : "turquoise"}>{trip.status.toLowerCase()}</Badge><ChevronRight className="text-karakoram-ink/30 transition group-hover:translate-x-1 group-hover:text-attabad-turquoise" /></div><h3 className="display-type mt-6 text-3xl leading-tight">{trip.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-karakoram-ink/68">{trip.vibe ?? "A thoughtful route through real places."}</p><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 border-t border-karakoram-ink/9 pt-4 text-xs font-semibold text-karakoram-ink/60"><span className="inline-flex items-center gap-1.5"><CalendarDays size={14} className="text-attabad-turquoise" /> {range(trip)}</span><span className="inline-flex items-center gap-1.5"><Sparkles size={14} className="text-attabad-turquoise" /> {trip.days.length} days</span>{trip.isPublic && <span className="inline-flex items-center gap-1.5"><Share2 size={14} className="text-rickshaw-magenta" /> Shared</span>}</div></Link>)}</div>}</div></section></>;
}
